
# Frame
base_frame: base_link
map_frame: map
odom_frame: odom

inverted_laser: false
throttle_scans: 1
map_update_interval: 1.0
maxUrange: 40.0
sigma: 0.15
#sigma: 0.05
kernelSize: 1
lstep: 0.005
astep: 0.001
iterations: 5
#lsigma: 0.3
lsigma: 0.05
ogain: 3.0
lskip: 0
minimumScore: 450.0
#minimumScore: 300.0
str: 0.0000
#str: 0.050
stt: 0.00050
#stt: 0.050
srr: 0.00001
#srr: 0.050
srt: 0.00001
#srt: 0.050
linearUpdate: 0.5
angularUpdate: 0.25
temporalUpdate: -1.0
resampleThreshold: 0.8
#particles: 30
particles: 5
xmin: -100.0
ymin: -100.0
xmax: 100.0
ymax: 100.0
delta: 0.05
#llsamplerange: 0.01
llsamplerange: 0.001
#llsamplestep: 0.01
llsamplestep: 0.001
#lasamplerange: 0.005
lasamplerange: 0.005
#lasamplestep: 0.005
lasamplestep: 0.0001
transform_publish_period: 0.05
occ_thresh: 0.10
maxRange: 40.0