
LOCALIZED_POSE_JSON="localized_pose.json"
POSE_PAIR_JSON="pose_pair.json"
KML_FILENAME="map.kml"
WORLD_TO_MAP_JSON="world_to_map.json"

RAW_WAYPOINT_FILENAME="waypoint.csv"
WAYPOINT_FILENAME="smooth_waypoint.csv"
DATAINFO_FILENAME="DATAINFO.txt"

PARAM_DIRNAME="PARAM_DIRNAME"

BAG_START="BAG_START"
BAG_DURATION="BAG_DURATION"
BAG_RATE="BAG_RATE"
BAG_WAIT="BAG_WAIT"
