
LOCALIZED_POSE_JSON="localized_pose.json"
POSE_PAIR_JSON="pose_pair.json"
KML_FILENAME="map.kml"
WORLD_TO_MAP_JSON="world_to_map.json"

RAW_WAYPOINT_FILENAME="waypoint.csv"
WAYPOINT_FILENAME="smooth_waypoint.csv"
DATAINFO_FILENAME="DATAINFO.txt"

PLANE_NUMBER="PLANE_NUMBER"
POSE_INITIALIZER="POSE_INITIALIZER"
INIT_VIA_GNSS="INIT_VIA_GNSS"

INIT_X_NAME="INIT_X"
INIT_Y_NAME="INIT_Y"
INIT_Z_NAME="INIT_Z"
INIT_ROLL_NAME="INIT_ROLL"
INIT_PITCH_NAME="INIT_PITCH"
INIT_YAW_NAME="INIT_YAW"

BAG_START="BAG_START"
BAG_DURATION="BAG_DURATION"
BAG_RATE="BAG_RATE"
BAG_WAIT="BAG_WAIT"
