
# Definition of Coordinate System.
frame_name:
  base_link: base_link
  map: map
  lidar: lidar
  odometry:
    imu: odom
    whl: odom
    ypspur: odom

planner_frame:
  global_cost_map:
    base: base_link
    global: map
  local_cost_map:
    base: base_link
    global: odom
  local_planner_map:
    global: odom

  

