
local_costmap:

  # Movebase
  inscribed_radius: 0.25
  circumscribed_radius: 0.30

  # Costmap2DROS
  # Frame
  global_frame: map
  robot_base_frame: base_link

  # Setting
  rolling_window: true
  track_unknown_space: false
  always_send_full_costmap: false

  # Hz
  transform_tolerance: 0.3
  update_frequency: 10.0
  publish_frequency: 10.0

  # Size
  width: 6.0
#  width: 10.0
  height: 6.0
#  height: 10.0
  resolution: 0.05
  origin_x: 0
  origin_y: 0

  plugins:
   - {name: static_layer,        type: "costmap_2d::StaticLayer"} 
   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}