
global_costmap:

  # Costmap2DROS
  # Frame
  global_frame: map
  robot_base_frame: base_link
  # Setting
  rolling_window: false
  track_unknown_space: true
  always_send_full_costmap: false
  # Hz
  transform_tolerance: 0.3
  update_frequency: 1.0
  publish_frequency: 0.5
  # Size
  width: 10
  height: 10
  resolution: 0.05
  origin_x: 0
  origin_y: 0

  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

  