
# Costmap2DROS
robot_radius: 0.3
#footprint: []
#footprint: [[0.27, 0.22], [0.27, -0.22], [-0.40, -0.22], [-0.40, 0.22]]
#footprint: [[0.27, 0.27], [0.27, -0.27], [-0.40, -0.27], [-0.40, 0.27]]
footprint_padding: 0.05

static_layer:
  enabled: true
  map_topic: /root_map_server/map
  unknown_cost_value: -1
  lethal_cost_threshold: 100
  track_unknown_space: true
  first_map_only: false
  subscribe_to_updates: false
  use_maximum: false
  trinary_costmap: true

obstacle_layer:
  # ObstacleLayer Common Setting.
  enabled: true
  footprint_clearing_enabled: true
  max_obstacle_height: 2.0
  combination_method: 1

  # ObstableLayer Setting
  #track_unknown_space: true
  track_unknown_space: false
  transform_tolerance: 0.5
  observation_sources: laser_scan_sensor
  combination_method: 1
  laser_scan_sensor: {topic: /urg_node/scan, sensor_frame: "lidar", observation_persistence: 0.0, 
                      expected_update_rate: 0.0, data_type: LaserScan, min_obstacle_height: 0.0, 
                      max_obstacle_height: 2.0, inf_is_valid: false, clearing: true, marking: true,
                      obstacle_range: 3.5, raytrace_range: 4.0}
  
  # VoxelLayer Setting
  origin_z: 0.0
  z_resolution: 0.2
  z_voxels: 10
  unknown_threshold: 15
  mark_threshold: 0
  publish_voxel_map: false

inflation_layer:
  enabled:              true
  cost_scaling_factor: 10.0 # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius: 0.05     # max. distance from an obstacle at which costs are incurred for planning paths.
  inflate_unknown: false
