
topic_name:

  zed:
    left:
      raw:
        cam_info: /zed/left/raw/camera_info
        color: /zed/left/raw/image_color
      rect:
        cam_info: /zed/left/rect/camera_info
        color: /zed/left/rect/image_color
    right: 
      raw:
        cam_info: /zed/right/raw/camera_info
        color: /zed/right/raw/image_color
      rect:
        cam_info: /zed/right/rect/camera_info
        color: /zed/right/rect/image_color

  sgm_cuda:
    disparity: /sgm_cuda/disparity

  stixel_cuda:
    stixel_img: /stixel_cuda/stixel_img