
# Frame
odom_frame_id: odom
base_frame_id: base_link
global_frame_id: map

# TF related
tf_broadcast: true

# Filter Parameters
min_particles: 500
max_particles: 5000
kld_err: 0.05
kld_z: 0.99
#update_min_d: 0.2
update_min_d: 0.1
#update_min_a: 0.2
update_min_a: 0.1
resample_interval: 1
transform_tolerance: 0.1
recovery_alpha_slow: 0.001
recovery_alpha_fast: 0.0

# Initial Pose Parameters
#initial_pose_x: 0.3
#initial_pose_y: 2.6
#initial_pose_a: 0.0
initial_cov_xx: 0.25
initial_cov_yy: 0.25
initial_cov_aa: 0.0685389

# Visualizatoin Parameters
gui_publish_rate: 10.0
save_pose_rate: 0.5

# Subscription Parameters
use_map_topic: false
first_map_only: false

# Laser Model Parameters
laser_min_range: -1.0
laser_max_range: -1.0
laser_max_beams: 30
laser_z_hit: 0.95
laser_z_short: 0.1
laser_z_max: 0.05
laser_z_rand: 0.05
laser_sigma_hit: 0.2
laser_lambda_short: 0.1
laser_likelihood_max_dist: 2.0
laser_model_type: likelihood_field

# Odometry Related Parameters
odom_model_type: diff-corrected
odom_alpha1: 0.100
odom_alpha2: 0.005
odom_alpha3: 0.020
odom_alpha4: 0.020
odom_alpha5: 0.003

# Beam Skip
do_beamskip: false
beam_skip_distance: 0.5
beam_skip_threshold: 0.3
beam_skip_error_threshold_: 0.9

# Data Processing
bag_scan_period: -1.0

# Warning
std_warn_level_x: 0.2
std_warn_level_y: 0.2
std_warn_level_yaw: 0.1

# Restore
restore_defaults: false