TebLocalPlannerROS:

  odom_topic: /odom
  map_frame: map

  # Trajectory
  teb_autosize: True
  dt_ref: 0.3
  dt_hysteresis: 0.1
  #min_samples: 3
  min_samples: 3
  max_samples: 500
  global_plan_overwrite_orientation: True
  allow_init_with_backwards_motion: False
  global_plan_viapoint_sep: -1
  via_points_ordered: false
  max_global_plan_lookahead_dist: 3.0
  global_plan_prune_distance: 1
  exact_arc_length: False
  force_reinit_new_goal_dist: 1
  #feasibility_check_no_poses: 5
  feasibility_check_no_poses: 10
  publish_feedback: False
  min_resolution_collision_check_angular: 3.14159
    
  # Robot
  # Tsukuba Challenge
  max_vel_x: 1.0
  # Home
  #max_vel_x: 0.4
  max_vel_x_backwards: 0.2
  max_vel_y: 0.1
  max_vel_theta: 0.3
  #Tsukuba Challlenge
  acc_lim_x: 1.0  
  #Home
  #acc_lim_x: 0.5
  acc_lim_y: 0.2
  acc_lim_theta: 0.5
  min_turning_radius: 0.0
  wheelbase: 0.4
  cmd_angle_instead_rotvel: false
  is_footprint_dynamic: false
  footprint_model: 
    type: circular
    radius: 0.3
    #front_offset: 0.2
    #front_radius: 0.2
    #line_end: [0.3, 0.0]
    #line_start: [-0.3, 0.0]
    #rear_offset: 0.2
    #rear_radius: 0.2
    #type: polygon
    #footprint: [[0.27, 0.22], [0.27, -0.22], [-0.40, -0.22], [-0.40, 0.22]]
    #footprint: [[0.27, 0.27], [0.27, -0.27], [-0.40, -0.27], [-0.40, 0.27]]

  # GoalTolerance
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  free_goal_vel: False
  complete_global_plan: True
    
  # Obstacles 
  #min_obstacle_dist: 0.25 # This value must also include our robot radius, since footprint_model is set to "point".
  min_obstacle_dist: 0.05
  #inflation_dist: 0.6
  inflation_dist: 0.2
  #dynamic_obstacle_inflation_dist: 0.6
  dynamic_obstacle_inflation_dist: 0.6
  costmap_obstacles_behind_robot_dist: 1.0
  include_dynamic_obstacles: true
  include_costmap_obstacles: true
  obstacle_poses_affected: 5
  legacy_obstacle_association: false
  obstacle_association_force_inclusion_factor: 1.5
  obstacle_association_cutoff_factor: 5
  costmap_converter_plugin: NONE
  costmap_converter_spin_thread: true
  costmap_converter_rate: 5

  # Optimization
  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: true
  optimization_verbose: false
  penalty_epsilon: 0.01
  weight_max_vel_x: 2
  weight_max_vel_y: 2
  weight_max_vel_theta: 1
  weight_acc_lim_x: 1
  weight_acc_lim_y: 1
  weight_acc_lim_theta: 1
  weight_kinematics_nh: 1000
  #weight_kinematics_forward_drive: 100
  weight_kinematics_forward_drive: 100000000
  weight_kinematics_turning_radius: 0.1
  weight_optimaltime: 1
  weight_shortest_path: 0
  #weight_obstacle: 50
  weight_obstacle: 100
  #weight_inflation: 0.1
  weight_inflation: 10.0
  weight_dynamic_obstacle: 10
  weight_dynamic_obstacle_inflation: 0.1
  weight_viapoint: 1
  weight_prefer_rotdir: 1
  weight_adapt_factor: 50
  obstacle_cost_exponent: 2.0
  #obstacle_cost_exponent: 10.0

  # Homotopy Class Planner
  enable_homotopy_class_planning: true
  enable_multithreading: true
  simple_exploration: false
  max_number_classes: 5
  selection_obst_cost_scale: 100.0
  #selection_prefer_initial_plan: 0.95
  selection_prefer_initial_plan: 0.6
  selection_viapoint_cost_scale: 100.0
  selection_cost_hysteresis: 1.0
  #selection_cost_hysteresis: 10.0
  selection_alternative_time_cost: false
  obstacle_keypoint_offset: 0.1
  obstacle_heading_threshold: 0.45
  roadmap_graph_samples: 15
  roadmap_graph_area_width: 6
  roadmap_graph_area_length_scale: 1.0
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  switching_blocking_period: 0.1
  #switching_blocking_period: 0.5
  viapoints_all_candidates: true
  visualize_hc_graph: false
  visualize_with_time_as_z_axis_scale: 0.0
  delete_detours_backwards: true
  detours_orientation_tolerance: 1.570795
  length_start_orientation_vector: 0.4
  #max_ratio_detours_duration_best_duration: 3.0
  max_ratio_detours_duration_best_duration: 20.0

  # Recovery
  shrink_horizon_backup: true
  shrink_horizon_min_duration: 10
  oscillation_recovery: true
  oscillation_v_eps: 0.1
  oscillation_omega_eps: 0.1
  oscillation_recovery_min_duration: 10
  oscillation_filter_duration: 10
