
# Move Base Setting.
base_global_planner: navfn/NavfnROS
base_local_planner: teb_local_planner/TebLocalPlannerROS
planner_frequency: 0.0
controller_frequency: 5.0
planner_patience: 5.0
controller_patience: 15.0
max_planning_retries: -1
oscillation_timeout: 1000.0
oscillation_distance: 0.5
#clearing_radius: 0.46
clearing_radius: 0.50
conservative_reset_dist: 3.0
shutdown_costmaps: false
clearing_rotation_allowed: true
recovery_behavior_enabled: true
restore_defaults: false