
odometry:
  standstill_thresh: 0.000001
  use_left_pls: true
  use_right_pls: true
  cycle_time: 0.01
  max_sync_diff: 6
  dist_buffer: 10
  imu_yaw_buffer: 1
  whl_yaw_buffer: 1
  use_odom_whl: false
  calc_offset: false
  #offset_gyro_z: -104
  offset_gyro_z: -93

imu_filter:
  fixed_frame: odom
  use_mag: false
  publish_tf: true
  reverse_tf: false
  constant_dt: 0.0
  publish_debug_topics: false
  gain_acc: 0.01
  gain_mag: 0.01
  do_bias_estimation: true
  bias_alpha: 0.01
  do_adaptive_gain: true
  orientation_stddev: 0.0
  #acc_conv_ratio: 
  #ang_conv_ratio:
  offset_acc_x: -706
  offset_acc_y: 752
  #offset_acc_z: 15183
  offset_acc_z: 1215
  offset_gyro_x: -274
  offset_gyro_y: 176
  offset_gyro_z: -90