
sgm:
  left:
    width: 1280
    height: 720
  right:
    width: 1280
    height: 720
  max_disp: 256
  p1: 10
  p2: 96
  max_sync_diff: 10
  sgm_freq: 0

stixel:
  stixel_img: true
  max_sync_diff: 200
  prob:
#    out: 0.15
    out: 0.01
    out_sky: 0.4
    ord: 0.2
    grav: 0.1
    blg: 0.04
#    ground_given_nexist: 0.36
    ground_given_nexist: 0.01
#    object_given_nexist: 0.28    
    object_given_nexist: 0.01
    sky_given_nexist: 0.36
    nexist_dis: 0.0
#    ground: 0.333
    ground: 0.5
#    object: 0.333
    object: 0.5
#    sky: 0.333
    sky: 0.0
#    sigma_disparity_object: 1.0
    sigma_disparity_object: 0.5
#    sigma_disparity_ground: 2.0
    sigma_disparity_ground: 0.5
    sigma_sky: 0.1
  vcam:
    v_hor: 360
    focal: 700.0
    baseline: 0.12
    camera_center_y: 360.0
    column_step: 5
    width_margin: 0
    camera_tilt: 0.0
    sigma_camera_tilt: 0.05
    camera_height: 0.6
    sigma_camera_height: 0.05
    alpha_ground: 0.0
  model:
    median_step: false
#    epsilon: 3.0
    epsilon: 1.0    
    range_object_z: 10.2